### ISSUE TITLE
DocSearch: 0 records

### ISSUE THREAD

**Issue by xxxsf** [algolia/docsearch-scraper#575]
My docserach.yml is:
```
name: docsearch

on:
  push:
    branches:
      - main
jobs:
  algolia:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get the content of docsearch.json as config
        id: algolia_config
        run: echo "::set-output name=config::$(cat docsearch.json | jq -r tostring)"

      - name: Run algolia/docsearch-scraper image
        env:
          ALGOLIA_APP_ID: ${{ secrets.APPLICATION_ID }}
          ALGOLIA_API_KEY: ${{ secrets.API_KEY }}
          CONFIG: ${{ steps.algolia_config.outputs.config }}
        run: |
          docker run \
            --env APPLICATION_ID=${ALGOLIA_APP_ID} \
            --env API_KEY=${ALGOLIA_API_KEY} \
            --env "CONFIG=${CONFIG}" \
            algolia/docsearch-scraper
```
When I run this yml on github Action, it occur this following problem, May I ask how to solve it please? 
thanks.
```
Run docker run \
Unable to find image 'algolia/docsearch-scraper:latest' locally
latest: Pulling from algolia/docsearch-scraper
25fa05cd42bd: Pulling fs layer
4f4fb700ef54: Pulling fs layer
862d5b51094d: Pulling fs layer
c2676b834996: Pulling fs layer
a86c726c37a1: Pulling fs layer
49ddaf3f242e: Pulling fs layer
cb1b8aba7015: Pulling fs layer
5d4756cec649: Pulling fs layer
492df993a698: Pulling fs layer
34595317c57c: Pulling fs layer
91a2b44d3612: Pulling fs layer
e896aff29962: Pulling fs layer
3461911b3af3: Pulling fs layer
5f6a69636a00: Pulling fs layer
f40d53392b51: Pulling fs layer
1efc12014f98: Pulling fs layer
1b3b12522358: Pulling fs layer
41df153fa64b: Pulling fs layer
51d41f384297: Pulling fs layer
c4a6d5f7f079: Pulling fs layer
[13](https://github.com/hellof2e/quark-design-docs/actions/runs/4509742416/jobs/7939860805#step:4:14)0c70ebad46: Pulling fs layer
69a3094e0d80: Pulling fs layer
bebacebdf011: Pulling fs layer
93ae9028de54: Pulling fs layer
384338c462b9: Pulling fs layer
c2676b834996: Waiting
a86c726c37a1: Waiting
49ddaf3f242e: Waiting
cb1b8aba7015: Waiting
5d4756cec649: Waiting
492df993a698: Waiting
34595317c57c: Waiting
91a2b44d3612: Waiting
e896aff29962: Waiting
3461911b3af3: Waiting
5f6a69636a00: Waiting
130c70ebad46: Download complete
bebacebdf011: Verifying Checksum
bebacebdf011: Download complete
69a3094e0d80: Verifying Checksum
69a3094e0d80: Download complete
93ae9028de54: Verifying Checksum
93ae9028de54: Download complete
384338c462b9: Verifying Checksum
384338c462b9: Download complete
492df993a698: Verifying Checksum
492df993a698: Download complete
25fa05cd42bd: Pull complete
4f4fb700ef54: Pull complete
862d5b51094d: Pull complete
c2676b834996: Pull complete
a86c726c37a1: Pull complete
49ddaf3f242e: Pull complete
cb1b8aba7015: Pull complete
5d4756cec649: Pull complete
492df993a698: Pull complete
34595317c57c: Pull complete
91a2b44d3612: Pull complete
e896aff29962: Pull complete
3461911b3af3: Pull complete
5f6a69636a00: Pull complete
f40d53392b51: Pull complete
1efc120[14](https://github.com/hellof2e/quark-design-docs/actions/runs/4509742416/jobs/7939860805#step:4:15)f98: Pull complete
1b3b12522358: Pull complete
41df[15](https://github.com/hellof2e/quark-design-docs/actions/runs/4509742416/jobs/7939860805#step:4:16)3fa64b: Pull complete
51d41f384297: Pull complete
c4a6d5f7f079: Pull complete
130c70ebad46: Pull complete
69a3094e0d80: Pull complete
bebacebdf011: Pull complete
93ae9028de54: Pull complete
384338c462b9: Pull complete
Digest: sha256:7bc1cd5aa4783bf24be9ddd6ef22a629b6b43e2[17](https://github.com/hellof2e/quark-design-docs/actions/runs/4509742416/jobs/7939860805#step:4:18)b3fa2[20](https://github.com/hellof2e/quark-design-docs/actions/runs/4509742416/jobs/7939860805#step:4:21)b6a0acbdeb83b8f8
Status: Downloaded newer image for algolia/docsearch-scraper:latest
> DocSearch: https://quark-design.hellobike.com/ 0 records)

Crawling issue: nbHits 0 for CNDoc
Error: Process completed with exit code 3.
```
